version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://dilshankmc91_db_user:Kmcd2344316@cluster0.vaqhggg.mongodb.net/MAS_Test01?retryWrites=true&w=majority
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app